/**
 * RefactorUtils.js
 *
 * Generates actionable shell scripts for "Refactoring Largo".
 * Handles Move logic and Import updates.
 */

export const generateRefactorScript = (building, targetFolder) => {
    if (!building || !building.path) return '# Error: Invalid building selected'

    const sourcePath = building.path
    const fileName = sourcePath.split('/').pop()
    const targetPath = `${targetFolder}/${fileName}`

    // 1. Safety Checks
    // 2. Create Target Directory
    // 3. Move File
    // 4. Update Imports (Mock using sed/ag for visual demonstration)

    // Note: In a real app, this would use AST analysis.
    // Here we generate a "Concept Script" for the user to review.

    return `#!/bin/bash
# Refactoring Plan: Move ${fileName}
# Generated by Code City Architect

echo "🔧 Starting Refactor: ${fileName} -> ${targetFolder}"

# 1. Create Target Directory
mkdir -p src/${targetFolder}

# 2. Move File
mv src/${sourcePath} src/${targetPath}

# 3. Update Imports (Heuristic)
# Find files that import this module and update the path
# (Warning: This is a rough heuristic, check diffs before committing!)

echo "🔍 Updating references..."

grep -rl "${fileName.replace(/\.[^/.]+$/, "")}" src/ | xargs sed -i '' "s|${sourcePath.replace(/\.[^/.]+$/, "")}|${targetPath.replace(/\.[^/.]+$/, "")}|g"

echo "✅ Refactor Complete! Please run tests."
`
}
